### ISSUE TITLE
node-json2html has a ReferenceError on import

### ISSUE THREAD

**Issue by satyanash** [moappi/json2html#46]
@moappi When trying to import `node-json2html`, we get a `ReferenceError`. Here is a minimum reproducible example:

``` shell
$ mkdir test-node && cd test-node
$ npm init
...
$ npm add node-json2html
...
```
``` javascript
$ node
Welcome to Node.js v12.13.1.
Type ".help" for more information.
> const json2html = require('node-json2html');
Thrown:
ReferenceError: json2html is not defined
    at Object.<anonymous> (/Users/<snip>/<snip>/test-node/node_modules/node-json2html/node.json2html.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
> global
Object [global] {
  global: [Circular],
  clearInterval: [Function: clearInterval],
  clearTimeout: [Function: clearTimeout],
  setInterval: [Function: setInterval],
  setTimeout: [Function: setTimeout] { [Symbol(util.promisify.custom)]: [Function] },
  queueMicrotask: [Function: queueMicrotask],
  clearImmediate: [Function: clearImmediate],
  setImmediate: [Function: setImmediate] {
    [Symbol(util.promisify.custom)]: [Function]
  },
  json2html: {
    version: '2.1.0',
    render: [Function: render],
    component: { add: [Function: add], get: [Function: get] },
    iHTML: [Function: iHTML],
    toText: [Function: toText],
    transform: [Function: render]
  }
}
```
Essentially, the library is being loaded correctly as we can see `json2html` object is successfully defined on `global`.
The export is failing on [line 14 of node.json2html.js](https://github.com/moappi/json2html/blob/4c7f2fe24f2bf06783eb8ee3575c238f8448a654/node.json2html.js#L14). 

Surprisingly, this does not happen if we use a different variable name:

``` javascript
$ node
> const j2h = require('node-json2html');
undefined
> j2h
{
  version: '2.1.0',
  render: [Function: render],
  component: { add: [Function: add], get: [Function: get] },
  iHTML: [Function: iHTML],
  toText: [Function: toText],
  transform: [Function: render]
}
```

I think @NavyaV01 was also facing this in #40.

**Comment by satyanash** [comment]
This is most likely because the global name conflicts with the name of the constant.
Perhaps, when used within node, the library should not use the global and simply export the top-level `json2html` instance?
